pool:
  vmImage: 'Ubuntu 16.04'
steps:
- task: AzureCLI@1
  displayName: 'Azure CLI'
  inputs:
    azureSubscription: 'Azure-Subscription'
    scriptLocation: inlineScript
    inlineScript: 'az acr build --registry $(acr_name) --image $(image_name):$(Build.BuildId) .'
